name=NIELIT Arduino UNO Practicals
version=1.0.2
author=Lovnish Verma
maintainer=Lovnish Verma
sentence=NIELIT Arduino UNO practical programs and examples.
paragraph=Educational practical programs for Arduino UNO covering GPIO, sensors, displays, EEPROM, Bluetooth, relay control and home automation.
category=Other
url=https://github.com/LovnishVerma/NIELIT-Arduino-UNO-Practicals
architectures=avr
